### ISSUE TITLE
different colour code for similar genes

### ISSUE THREAD

**Issue by rob2go** [gamcil/clinker#5]
First of all I want to thank you for the amazing tool.
I have a question. 
During my comparison, very similar genes had different colours, as you can see at the following picture

<img width="553" alt="Screen Shot " src="https://user-images.githubusercontent.com/16964045/98452817-1dbf2380-2153-11eb-98d9-c4f39b4edac3.png">

Any clue?

**Comment by gamcil** [comment]
Oh that's weird! Seems like something is going wrong when it's generating the similar gene groups. Could you provide the files you used in this comparison so I could have a look?

**Comment by rob2go** [comment]
Yes, sure. I'd prefer to send it privately. Can you tell me an email address?

**Comment by gamcil** [comment]
Sure, send to cameron.gilchrist@research.uwa.edu.au

**Comment by gamcil** [comment]
Fixed with https://github.com/gamcil/clinker/commit/8d1e001874afb5425bdce00d5a5d40e6480494fa (https://github.com/gamcil/clustermap.js/commit/2ae4adb00670bc2192b054fb6924485d448a71c0)

**Comment by Beren95** [comment]
Hi there!

First of all i'm so grateful  for this tool, thanks

I'm getting the same problem, and i´m kind new in the usage of github so not sure if i´m doing it right

I downloaded the files from the repository, then i changed the code as indicated in 8d1e001 an then installed it with pip
and im still getting se same coloring issues 

could you help me with this?
